<a href="https://colab.research.google.com/github/Giuseppe0075/PyTorch-Learning/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First lesson of PyTorch

In [3]:
import torch
print(torch.__version__)

2.9.0+cu126


#Creating Tensor

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [21]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
MATRIX[1][1]

tensor(10)

In [39]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        ]])
TENSOR

tensor([[[1, 2, 3]]])

In [40]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 1, 3])

In [35]:
TENSOR[1]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random tensors

In [54]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0225, 0.5399, 0.7975, 0.9012],
        [0.6467, 0.6135, 0.4823, 0.6259],
        [0.5479, 0.3359, 0.4071, 0.6130]])

In [55]:
random_tensor.ndim

2

In [56]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [57]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [67]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=random_tensor)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor dType

In [81]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=True)
float_32_tensor

tensor([3., 6., 9.], requires_grad=True)

In [82]:
float_32_tensor.dtype

torch.float32