<a href="https://colab.research.google.com/github/Giuseppe0075/PyTorch-Learning/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First lesson of PyTorch

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


### Creating Tensor

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1][1]

tensor(10)

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        ]])
TENSOR

tensor([[[1, 2, 3]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 1, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3]])

### Random tensors

In [19]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8425, 0.1142, 0.9230, 0.0682],
        [0.3567, 0.5942, 0.2941, 0.6971],
        [0.2771, 0.5462, 0.6183, 0.3741]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [26]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=random_tensor)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor dType

In [44]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32

In [46]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [49]:
tensor = torch.rand(3,4)
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (operations)

In [65]:
# Create a tensor
tensor = torch.rand(size=(10,10), dtype=torch.float32)

In [66]:
%%time
# Addition
print(tensor + 10)
# Subtraction
print(tensor - 10)
# Multiplication
print(tensor * 10)
# Division
print(tensor/10)
# Element wise multiplication
print(tensor * tensor)
# Dot product (matrix multiplication)
print(tensor @ tensor)

tensor([[10.2450, 10.5435, 10.4869, 10.7253, 10.7796, 10.7582, 10.1348, 10.4687,
         10.8708, 10.3637],
        [10.5444, 10.7650, 10.6514, 10.5387, 10.8252, 10.6090, 10.6926, 10.1958,
         10.9634, 10.4466],
        [10.7510, 10.2640, 10.8856, 10.2620, 10.1405, 10.0297, 10.2319, 10.7123,
         10.6951, 10.6229],
        [10.5650, 10.1519, 10.7663, 10.2817, 10.7280, 10.4707, 10.1343, 10.3829,
         10.1833, 10.2175],
        [10.9708, 10.3189, 10.9438, 10.8536, 10.3668, 10.6694, 10.8006, 10.5945,
         10.5273, 10.8541],
        [10.4387, 10.9092, 10.4871, 10.6216, 10.9569, 10.9695, 10.4010, 10.3060,
         10.6179, 10.0743],
        [10.6150, 10.6761, 10.1037, 10.3255, 10.0749, 10.6217, 10.1841, 10.2737,
         10.5926, 10.2410],
        [10.1311, 10.9039, 10.3645, 10.4620, 10.5703, 10.3688, 10.4989, 10.8150,
         10.8113, 10.5943],
        [10.0721, 10.3162, 10.5816, 10.9876, 10.2554, 10.8546, 10.9190, 10.9886,
         10.0487, 10.1083],
        [10.6937, 1

In [67]:
%%time
# With PyTorch in-built functions
print(tensor.add(10))
print(tensor.sub(10))
print(tensor.mul(10))
print(tensor.div(10))
print(tensor.mul(tensor))
print(tensor.matmul(tensor))

tensor([[10.2450, 10.5435, 10.4869, 10.7253, 10.7796, 10.7582, 10.1348, 10.4687,
         10.8708, 10.3637],
        [10.5444, 10.7650, 10.6514, 10.5387, 10.8252, 10.6090, 10.6926, 10.1958,
         10.9634, 10.4466],
        [10.7510, 10.2640, 10.8856, 10.2620, 10.1405, 10.0297, 10.2319, 10.7123,
         10.6951, 10.6229],
        [10.5650, 10.1519, 10.7663, 10.2817, 10.7280, 10.4707, 10.1343, 10.3829,
         10.1833, 10.2175],
        [10.9708, 10.3189, 10.9438, 10.8536, 10.3668, 10.6694, 10.8006, 10.5945,
         10.5273, 10.8541],
        [10.4387, 10.9092, 10.4871, 10.6216, 10.9569, 10.9695, 10.4010, 10.3060,
         10.6179, 10.0743],
        [10.6150, 10.6761, 10.1037, 10.3255, 10.0749, 10.6217, 10.1841, 10.2737,
         10.5926, 10.2410],
        [10.1311, 10.9039, 10.3645, 10.4620, 10.5703, 10.3688, 10.4989, 10.8150,
         10.8113, 10.5943],
        [10.0721, 10.3162, 10.5816, 10.9876, 10.2554, 10.8546, 10.9190, 10.9886,
         10.0487, 10.1083],
        [10.6937, 1

### One of the most common errors in deep learning: shape error

In [77]:
# The inner dimensions must match:
tensor1 = torch.rand(size=(10,2))
tensor2 = torch.rand(size=(3,2))
try:
  tensor1.matmul(tensor2)
except Exception as e:
  print(e)

mat1 and mat2 shapes cannot be multiplied (10x2 and 3x2)


In [80]:
# The result has the shape of the outer dimensions
tensor2 = torch.rand(size=(2,1))
print(tensor1.matmul(tensor2), tensor1.matmul(tensor2).shape)

tensor([[0.2948],
        [0.8547],
        [0.6111],
        [0.2820],
        [0.8085],
        [0.8162],
        [0.1039],
        [0.5340],
        [0.6603],
        [0.4845]]) torch.Size([10, 1])


In [87]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
print(tensor_A.shape, tensor_B.shape)
try:
  torch.mm(tensor_A, tensor_B)
except Exception as e:
  print(e)

torch.Size([3, 2]) torch.Size([3, 2])
mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [88]:
# Transposition
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [90]:
# And now it works!
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Finding the min, max, mean, sum, etc

In [92]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [102]:
# Min
torch.min(x), x.min()

(tensor(0.), tensor(0.))

In [103]:
# Max
torch.max(x), x.max()

(tensor(90.), tensor(90.))

In [104]:
# Mean (Error!!)
try:
  x.mean()
except Exception as e:
  print(e)

In [105]:
# Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [106]:
# Sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

### Finding min, max Position

In [109]:
# Minimum position
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [110]:
# Maximum position
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - concatenate multiple tensors on a certain direction
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueez - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted in a certain way

In [11]:
# Create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [18]:
# Add an extra dimension (n*m must be equal to the number of elements in the tensor)
x_reshaped = x.reshape(3,4)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(6,2)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(2, 6)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(12)
print(x_reshaped, x_reshaped.shape)

try:
  x_reshaped = x.reshape(1,13)
except Exception as e:
  print(e)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) torch.Size([3, 4])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]]) torch.Size([2, 6])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])
shape '[1, 13]' is invalid for input of size 12


In [19]:
# Change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [20]:
# Changing z changes x (z is a pointer to x)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [29]:
# Stack tensors
z_stacked = torch.stack([x,x,x,x], dim=1)
print(z_stacked)

reshaped_x = x.reshape(2,6)
z_stacked = torch.stack([reshaped_x,reshaped_x,reshaped_x,reshaped_x], dim=2)
print(z_stacked)

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])
tensor([[[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.]],

        [[ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.],
         [11., 11., 11., 11.],
         [12., 12., 12., 12.]]])


In [33]:
# Squeeze
x = torch.tensor([[[1,2,3]],
                  [[1,2,3]]])
print(x.shape)
x_squeezed = x.squeeze()
print(x_squeezed, x_squeezed.shape)

# You can also specify the dimension (but only the ones with size = 1 will be squeezed)
x_squeezed = x.squeeze(dim=1)
print(x_squeezed, x_squeezed.shape)


# If the specified dimension is not of size 1, the tensor is unchanged
x_unsqueezed = x.squeeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)


torch.Size([2, 1, 3])
tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])
tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])
tensor([[[1, 2, 3]],

        [[1, 2, 3]]]) torch.Size([2, 1, 3])


In [36]:
# Unsqueeze
print(x.shape)

x_unsqueezed = x.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)

torch.Size([2, 1, 3])
tensor([[[[1, 2, 3]],

         [[1, 2, 3]]]]) torch.Size([1, 2, 1, 3])


In [49]:
# Permute
x = torch.rand(size=(1920,1080,3)) #[width, height, colour]
print(x.shape)

permuted_x = x.permute(2,0,1) #[colour, width, height]
print(permuted_x.shape)

# Dimensions must be between the size of the tensor
try:
  permuted_x = x.permute(0,4,1)
except Exception as e:
  print(e)

# Dimensions must be different from each other
try:
  permuted_x = x.permute(0,1,0)
except Exception as e:
  print(e)

torch.Size([1920, 1080, 3])
torch.Size([3, 1920, 1080])
Dimension out of range (expected to be in range of [-3, 2], but got 4)
permute(): duplicate dims are not allowed.


### Indexing

In [51]:
# Create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
# Index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
# Index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [56]:
# Index on the third dimension (dim=2)
x[0][1][0], x[0,1,0]

(tensor(4), tensor(4))

In [57]:
# Using `x:y` to select range of a target dimension (living blank mean from  start to end)
x[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [69]:
x[:,1,:]

tensor([[4, 5, 6]])

In [70]:
x[0,2,2]

tensor(9)

In [71]:
x[0,:,2]

tensor([3, 6, 9])

### PyTorch tensors & NumPy

In [74]:
# From NumPy to Torch
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array, tensor)

# Default numpy dtype = float64
print(tensor.type(torch.float32))

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6., 7.])


In [75]:
# Change the value of array
array = array + 1
print(array, tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [77]:
# From Torch to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, numpy_tensor, numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.] float32


In [78]:
# Change the value of tensor
tensor = tensor + 1
print(tensor, numpy_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


### Reproducibility
* Removing (reducing) randomness in PyTorch

In [85]:
# Normally we can't generate equal tensors
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2783, 0.4820, 0.8198, 0.9971],
        [0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417]])
tensor([[0.7262, 0.7011, 0.2038, 0.6511],
        [0.7745, 0.4369, 0.5191, 0.6159],
        [0.8102, 0.9801, 0.1147, 0.3168]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
import torch

# Set a random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# Have to set the manual seed for each random method used
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs

1. Getting a GPU
-----------------------------------------
1. Use Google Colab
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure

2. Test for GPU availability
----

In [2]:
# Test for the runtime environment
!nvidia-smi

Sat Dec 13 11:53:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

3. Setup device agnostic code
---

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

In [13]:
# Default tensor (explicit cpu device)
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [15]:
# Putting it on a GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')


4. Moving tensors back to the CPU
---

In [17]:
# If tensor is on GPU, can't transform it to NumPy
try:
  tensor_on_gpu.numpy()
except Exception as e:
  print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [18]:
# Setting it to the CPU will fix the error
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Excercises

In [2]:
import torch

1. Learn the documentation of `torch.Tensor` and `torch.cuda`

2. Create a random tensor with shape `(7, 7)`.

In [3]:
tensor1 = torch.rand(size=(7,7))
tensor1

tensor([[0.2192, 0.0934, 0.2957, 0.9219, 0.2097, 0.2449, 0.0768],
        [0.3685, 0.2692, 0.8916, 0.9934, 0.4517, 0.6657, 0.0681],
        [0.5986, 0.3432, 0.4202, 0.4418, 0.8574, 0.1519, 0.0314],
        [0.1161, 0.8111, 0.7681, 0.2699, 0.6693, 0.7098, 0.6234],
        [0.5448, 0.4592, 0.3686, 0.2714, 0.1550, 0.8481, 0.5271],
        [0.7101, 0.9049, 0.2701, 0.1275, 0.7197, 0.8049, 0.4459],
        [0.4851, 0.5595, 0.4877, 0.0687, 0.0901, 0.4116, 0.3159]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)`.

In [4]:
tensor2 = torch.rand(size=(1,7))
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3

tensor([[0.8344],
        [1.9082],
        [1.7686],
        [2.2810],
        [1.5682],
        [2.2098],
        [1.3036]])

4. Set the random seed to `0` and do exercises 2 & 3 over again.

In [5]:
RANDOM_SEED = 1
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size=(7,7))
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(size=(1,7))
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3

tensor([[2.1526],
        [2.0592],
        [1.7513],
        [1.5907],
        [1.2780],
        [2.0656],
        [2.1214]])

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [8]:
torch.cuda.manual_seed(1234)
tensor1 = torch.rand(size=(3,3), device="cuda")

torch.cuda.manual_seed(1234)
tensor2 = torch.rand(size=(3,3), device="cuda")

print(tensor1.eq(tensor2))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]], device='cuda:0')


6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)

In [9]:
torch.manual_seed(1234)
tensor1 = torch.rand(size=(2,3), device='cuda')

torch.manual_seed(1234)
tensor2 = torch.rand(size=(2,3), device='cuda')

print(tensor1.eq(tensor2))

tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
tensor3 = torch.matmul(tensor1, tensor2.reshape(3,2))
tensor3

tensor([[0.6085, 1.1727],
        [0.4969, 1.6667]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [14]:
print("Max value: ", tensor3.max())
print("Min value: ", tensor3.min())

Max value:  tensor(1.6667, device='cuda:0')
Min value:  tensor(0.4969, device='cuda:0')


9. Find the maximum and minimum index values of the output of 7.

In [16]:
print("Max value index: ", tensor3.argmax())
print("Min value index: ", tensor3.argmin())

Max value index:  tensor(3, device='cuda:0')
Min value index:  tensor(2, device='cuda:0')


10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [18]:
torch.manual_seed(7)
tensor1 = torch.rand(size=(1,1,1,10))

torch.manual_seed(7)
tensor2 = torch.rand(10)

print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
